name: v1-workflow

on:
  workflow_dispatch:
  push:
    branches: ['main']

permissions:
  contents: write
  pull-requests: write
  packages: read

jobs:
  Call-Code-Coverage:
    uses: DotFoods/actions/blob/develop/.github/workflows/unit-test-code-coverage.yml@develop
    with:
      unit-test-folder: 'AddNumbersApp/AddNumbersApp.Test'
      unit-test-project-name: 'AddNumbersApp.Test.csproj'
    secrets: inherit

  Call-Build:
    uses: DotFoods/actions/.github/workflows/functions-build.yml@test-ty
    with:
      dotnet-version: '8.0.x'
      project-path-and-name: 'AddNumbersApp/AddNumbersApp.csproj'
    secrets: inherit

  Upload-Scan:
    needs: [Call-Code-Coverage, Call-Build]
    uses: DotFoods/actions/.github/workflows/veracode-upload-scan.yml@main
    with:
      dotnet-version: '8.0.x'
      project-path: 'AddNumbersApp/AddNumbersApp.csproj'
      appname: 'AddNumbersApp'
      version: 'AddNumbersApp.v1.${{ github.run_number }}'
    secrets: inherit

  Call-Deploy-DEV:
    needs: [Upload-Scan]
    uses: DotFoods/actions/.github/workflows/functions-deploy.yml@main
    with:
      environment: dev
      function-app-name: 'test-function-app-cicd'
      slot-name: 'staging'
    secrets:
      publishProfileSecret: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

  Call-Swap-DEV:
    needs: [Call-Deploy-DEV]
    uses: DotFoods/actions/.github/workflows/functions-swap.yml@main
    with:
      environment: dev
      function-app-name: 'test-function-app-cicd'
      resource-group: 'rg-billing-discrepancy-dev'
      source-slot: 'staging'
      target-slot: 'production'
   
  Call-Release:
    needs: [Call-Swap-DEV]
    uses: DotFoods/actions/.github/workflows/gitflow-release.yml@main
    with:
      developBranch: ${{ github.base_ref }}
      mainBranch: 'main-v1'
    secrets: inherit