name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # Set this to the path of your Azure Function project, defaults to the repository root
  DOTNET_VERSION: '8.0.x' # Set this to the .NET version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup .NET Core ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

      - name: Build the project
        run: dotnet build --configuration Release ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

      - name: Run tests
        run: dotnet test --configuration Release ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

      - name: Publish the project
        run: dotnet publish --configuration Release --output ./output ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

      - name: 'Deploy to Azure Function App'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          slot-name: 'dev'
          package: './output'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
