# # Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# # More GitHub Actions for Azure: https://github.com/Azure/actions

# name: Build and deploy dotnet core project to Azure Function App - test-function-app-cicd

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# env:
#   AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
#   DOTNET_VERSION: '8.0.x' # set this to the dotnet version to use

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
    
#     steps:
#       - name: 'Checkout GitHub Action'
#         uses: actions/checkout@v4

#       - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
#         uses: actions/setup-dotnet@v1
#         with:
#           dotnet-version: ${{ env.DOTNET_VERSION }}

#       - name: 'Resolve Project Dependencies Using Dotnet'
#         shell: bash
#         run: |
#           pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
#           dotnet build --configuration Release --output ./output
#           popd
      
#       - name: 'Run Azure Functions Action'
#         uses: Azure/functions-action@v1
#         id: fa
#         with:
#           app-name: 'test-function-app-cicd'
#           slot-name: 'Production'
#           package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
#           publish-profile: ${{ secrets.AzureAppService_PublishProfile_c37715c35bee4ce3881286a56b4e132d }}


on:
  push:
    branches:
      - master  # Replace with your default branch if necessary

env:
  AZURE_FUNCTIONAPP_NAME: 'test-function-app-cicd'   # Set this to your Azure Function App name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'  # Update this to the correct path to your .csproj file
  DOTNET_VERSION: '8.0.x'                   # Set this to the .NET version you are using

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'List Project Directory'
        run: ls -la ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}  # List files in the project directory to confirm presence of .csproj

      - name: 'Restore Project Dependencies'
        run: |
          dotnet restore ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/*.csproj

      - name: 'Build Project'
        run: |
          dotnet build --configuration Release --output ./output ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/*.csproj

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: './output'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
