name: v1-workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches: ['develop-v1']

permissions:
  contents: write
  pull-requests: write
  packages: read

jobs:
  Call-Code-Coverage:
    uses: DotFoods/actions/.github/workflows/unit-test-code-coverage.yml@develop
    with:
      unit-test-folder: './AddNumersApp.Test'
      unit-test-project-name: 'AddNumersApp.Test.csproj'
    secrets: inherit

  Call-Build:
    uses: DotFoods/actions/.github/workflows/functions-build.yml@test-ty
    with:
      dotnet-version: '8.0.x'
      project-path-and-name: 'AddNumersApp/AddNumersApp.csproj'
    secrets: inherit


  Upload-Scan:
    needs: [Call-Code-Coverage, Call-Build]
    uses: DotFoods/actions/.github/workflows/veracode-upload-scan.yml@main
    with:
        dotnet-version: '8.0.x'
        project-path: ''AddNumersApp/AddNumersApp.csproj''
        appname: 'AddNumersApp'
        version: 'AddNumersApp.v1.${{ github.run_number }}'
    secrets: inherit    

  Call-Deploy-DEV:
    needs: [Upload-Scan]
    uses: DotFoods/actions/.github/workflows/functions-deploy.yml@main
    with:
      environment: dev
      function-app-name: 'test-function-app-cicd
      slot-name: 'staging'
    secrets:
      publishProfileSecret: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

  Call-Swap-DEV:
    needs: [Call-Deploy-DEV]
    uses: DotFoods/actions/.github/workflows/functions-swap.yml@main
    with:
      environment: dev
      function-app-name: 'test-function-app-cicd'
      resource-group: 'rg-billing-discrepancy-dev'
      source-slot: 'staging'
      target-slot: 'production'
    secrets:
      azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}