on:
  push:
    branches:
      - master  # Replace with your default branch if necessary

env:
  AZURE_FUNCTIONAPP_NAME: 'your-app-name'   # Set this to your Azure Function App name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './path/to/your/project'  # Update this path to your .csproj directory
  DOTNET_VERSION: '8.0.x'                   # Set this to the dotnet version you are using

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Restore and Build Project'
        run: |
          dotnet restore ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/*.csproj
          dotnet build --configuration Release --output ./output ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/*.csproj

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: './output'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
