name: v1-workflow

on:
   push:
     branches:
       - main
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches: ['main']

permissions:
  pull-requests: write
  packages: read
  contents: write

jobs:
  dev-build:
    uses: DotFoods/actions/.github/workflows/functions-build.yml@main
    with:
      dotnet-version: '8.0.x'
      project-path-and-name: 'AddNumbersApp/AddNumbersApp.csproj'
    secrets: inherit
    
  upload-scan:
    needs: [dev-build]
    uses: DotFoods/actions/.github/workflows/veracode-upload-scan.yml@main
    with:
      dotnet-version: '8.0.x'
      project-path: 'AddNumbersApp/AddNumbersApp.csproj'
      appname: 'test-function-app-cicd'
      version: 'test-function-app-cicd.v1.${{ github.run_number }}'
    secrets: inherit
    
  deploy-dev:
    needs: [upload-scan]
    uses: DotFoods/actions/.github/workflows/functions-deploy.yml@main
    with:
      environment: dev
      function-app-name: 'test-function-app-cicd'
      slot-name: 'staging'
    secrets:
      publishProfileSecret: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

  swap-dev:
    needs: [deploy-dev]
    uses: DotFoods/actions/.github/workflows/functions-swap.yml@main
    with:
      environment: dev
      function-app-name: 'test-function-app-cicd'
      resource-group: 'rg-billing-discrepancy-dev'
      source-slot: 'staging'
      target-slot: 'production'
    secrets:
      azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}

  swap-prod:
    needs: [swap-dev]
    uses: DotFoods/actions/.github/workflows/functions-swap.yml@main
    with:
      environment: prod
      function-app-name: 'func-pim-archive-storage-prod'
      resource-group: 'rg-esl-prod'
      source-slot: 'staging'
      target-slot: 'production'
    secrets:
      azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}

  release:
    needs: [swap-prod]
    uses: DotFoods/actions/.github/workflows/gitflow-release.yml@main
    with:
      developBranch: 'develop-v1'
      mainBranch: 'main-v1'
    secrets: inherit
