name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change to your default branch if needed
  pull_request:
    branches:
      - main  # Change to your default branch if needed

jobs:
  build:
    runs-on: ubuntu-latest #hiii

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' 

    - name: Restore dependencies
      run: dotnet restore ./AddNumbersApp/AddNumbersApp.csproj

    - name: Build the project
      run: dotnet build --configuration Release ./AddNumbersApp/AddNumbersApp.csproj

    - name: Run tests
      run: dotnet test ./AddNumbersApp.Tests/AddNumbersApp.Tests.csproj --configuration Release

    - name: Deploy
      run: |
        echo "Deploying application..."
        # Add your deployment commands here, e.g., publish, deploy to Azure, etc.
