name: CI/CD Pipeline for Azure Function App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AZURE_FUNCTIONAPP_NAME: 'test-function-app-cicd'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore ./AddNumbersApp/AddNumbersApp.csproj

    - name: Build
      run: dotnet build --configuration Release ./AddNumbersApp/AddNumbersApp.csproj

    - name: Test
      run: dotnet test ./AddNumbersApp.Tests/AddNumbersApp.Tests.csproj --configuration Release

    - name: Publish
      run: dotnet publish --configuration Release --output ./output ./AddNumbersApp/AddNumbersApp.csproj

    

    - name: 'Deploy to Azure Function App'
      uses: Azure/functions-action@v1.5.0
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: './output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        respect-pom-xml: false
        respect-funcignore: false
        scm-do-build-during-deployment: false
        enable-oryx-build: false
        remote-build: false

    