name: v1-workflow

on:

  workflow_dispatch:
  pull_request:
    types: [closed]
    branches: ['develop-v1']

permissions:
  contents: write
  pull-requests: write
  packages: read

jobs:

  Upload-Scan:
    needs: [Call-Code-Coverage, Call-Build]
    uses: DotFoods/actions/.github/workflows/veracode-upload-scan-arv.yml@main
    with:
      dotnet-version: '8.0.x'
      project-path: 'AddNumbersApp/AddNumbersApp.csproj'
      appname: 'AddNumbersApp'
      version: 'AddNumbersApp.v1.${{ github.run_number }}'
    secrets: inherit    


  deploy-dev:
    needs: [upload-scan]
    uses: ./.github/workflows/dotnet-desktop.yml
    with:
      environment: 'development'
    secrets:
      publishProfileSecret: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
