name:Azure Function App - test-function-app-cicd

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './AddNumbersApp'
  DOTNET_VERSION: '8.0.x'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup .NET ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Build and Publish'
        run: |
          pushd "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release -o ./publish
          popd

      - name: Run Tests
        run: dotnet test ./AddNumbersApp.Tests/AddNumbersApp.Tests.csproj --configuration Release

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Dev Slot
        uses: Azure/functions-action@v1
        with:
          app-name: 'test-function-app-cicd-dev'
          slot-name: 'staging'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/publish'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_DEV_PUBLISH_PROFILE }}

  swap-dev:
    needs: deploy-dev
    runs-on: ubuntu-latest
    steps:
      - name: Swap Dev Slot to Production
        uses: Azure/CLI@v1
        with:
          inlineScript: |
            az functionapp deployment slot swap \
              --resource-group my-resource-group \
              --name test-function-app-cicd-dev \
              --slot staging \
              --target-slot production
          azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}

  deploy-qa:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to QA Slot
        uses: Azure/functions-action@v1
        with:
          app-name: 'test-function-app-cicd-qa'
          slot-name: 'staging'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/publish'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_QA_PUBLISH_PROFILE }}